import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextAuthProvider from './Provider'
import Header from '@/components/Header'
import { AppProvider } from '@/store/context'
import Modal from '@/components/Modal'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Instagram Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-[#f2f2f2] no-scrollbar`}>
        <NextAuthProvider>
          <AppProvider>
            <Header />
            <main
              className={`md:relative w-full lg:max-w-[84%] md:left-[7%] md:max-w-[93%] lg:left-[16%] overflow-hidden`}
            >
              {children}
            </main>
            <Modal />
          </AppProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
