import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { Inter } from 'next/font/google';
import './globals.css';
import NextAuthProvider from './Provider';
import Header from '@/components/Header';
import { AppProvider } from '@/store/context';
import Modal from '@/components/Modal';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Instagram Clone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-black text-[#f2f2f2] no-scrollbar`}
      >
        <NextAuthProvider>
          <AppProvider>
            <Header />
            <main
              className={`md:relative w-full mb-20 md:max-w-[84%] md:left-[16%]`}
            >
              {children}
            </main>
            <Modal />
          </AppProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
